name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: "maven@java17"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        showcase:
          - "block-kit"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: "adopt"
      - name: Run tests
        run: |
          cd "${{ matrix.showcase }}"
          mvn --batch-mode spotless:check
          mvn --batch-mode test -Dspotless.apply.skip
